#define LPOG_UNKNOWN_255_STR "Unknown"
#define LPOG_NOTHING_0_STR "Nothing"
#define LPOG_START_1_STR "Start"
#define LPOG_SCREEN_WRITE_START_2_STR "Screen write start"
#define LPOG_INITIALIZED_PINS_3_STR "Pins initialized"
#define LPOG_SCREEN_INIT_4_STR "Screen initialized"
#define LPOG_SCREEN_FIRST_ACTION_5_STR "Screen flushing done"
#define LPOG_SCREEN_END_6_STR "Screen end"
#define LPOG_SCREEN_POWEROFF_7_STR "Screen power off"
#define LPOG_ERROR_8_STR "Lp core ERROR"