/**
* Copyright (c) 2024 Bosch Sensortec GmbH. All rights reserved.
*
* BSD-3-Clause
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
* 1. Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
* 2. Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the distribution.
*
* 3. Neither the name of the copyright holder nor the names of its
*    contributors may be used to endorse or promote products derived from
*    this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*
* @file       bma530_context.h
* @date       2024-07-29
* @version    v4.2.0
*
*/

#ifndef _BMA530_CONTEXT_H
#define _BMA530_CONTEXT_H

/*! CPP guard */
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/****************************** Header files **********************************/
/******************************************************************************/

#include "bma530.h"

/******************************************************************************/
/********************* Macros for context parameters **************************/
/******************************************************************************/
#define BMA530_GENERIC_INTERRUPT1_1_GI1_SLOPE_THRES_S       UINT16_C(15)
#define BMA530_GENERIC_INTERRUPT1_1_GI1_SLOPE_THRES_W       UINT16_C(13)
#define BMA530_GENERIC_INTERRUPT1_1_GI1_SLOPE_THRES_H       UINT16_C(12)

#define BMA530_GENERIC_INTERRUPT1_2_GI1_HYSTERESIS_S        UINT16_C(3)
#define BMA530_GENERIC_INTERRUPT1_2_GI1_HYSTERESIS_W        UINT16_C(2)
#define BMA530_GENERIC_INTERRUPT1_2_GI1_HYSTERESIS_H        UINT16_C(4)

#define BMA530_GENERIC_INTERRUPT2_1_GI2_SLOPE_THRES_S       UINT16_C(15)
#define BMA530_GENERIC_INTERRUPT2_1_GI2_SLOPE_THRES_W       UINT16_C(12)
#define BMA530_GENERIC_INTERRUPT2_1_GI2_SLOPE_THRES_H       UINT16_C(8)

#define BMA530_GENERIC_INTERRUPT2_2_GI2_HYSTERESIS_S        UINT16_C(3)
#define BMA530_GENERIC_INTERRUPT2_2_GI2_HYSTERESIS_W        UINT16_C(2)
#define BMA530_GENERIC_INTERRUPT2_2_GI2_HYSTERESIS_H        UINT16_C(1)

#define BMA530_STEP_COUNTER_2_ENVELOPE_UP_THRES_S           UINT16_C(306)
#define BMA530_STEP_COUNTER_2_ENVELOPE_UP_THRES_W           UINT16_C(301)
#define BMA530_STEP_COUNTER_2_ENVELOPE_UP_THRES_H           UINT16_C(307)

#define BMA530_STEP_COUNTER_3_ENVELOPE_UP_DECAY_COEFF_S     UINT16_C(61900)
#define BMA530_STEP_COUNTER_3_ENVELOPE_UP_DECAY_COEFF_W     UINT16_C(63400)
#define BMA530_STEP_COUNTER_3_ENVELOPE_UP_DECAY_COEFF_H     UINT16_C(61932)

#define BMA530_STEP_COUNTER_4_ENVELOPE_DOWN_THRES_S         UINT16_C(132)
#define BMA530_STEP_COUNTER_4_ENVELOPE_DOWN_THRES_W         UINT16_C(315)
#define BMA530_STEP_COUNTER_4_ENVELOPE_DOWN_THRES_H         UINT16_C(133)

#define BMA530_STEP_COUNTER_5_ENVELOPE_DOWN_DECAY_COEFF_S   UINT16_C(55608)
#define BMA530_STEP_COUNTER_5_ENVELOPE_DOWN_DECAY_COEFF_W   UINT16_C(62902)
#define BMA530_STEP_COUNTER_5_ENVELOPE_DOWN_DECAY_COEFF_H   UINT16_C(55706)

#define BMA530_STEP_COUNTER_6_ACC_MEAN_DECAY_COEFF_S        UINT16_C(60104)
#define BMA530_STEP_COUNTER_6_ACC_MEAN_DECAY_COEFF_W        UINT16_C(63102)
#define BMA530_STEP_COUNTER_6_ACC_MEAN_DECAY_COEFF_H        UINT16_C(62260)

#define BMA530_STEP_COUNTER_7_STEP_DUR_MEAN_DECAY_COEFF_S   UINT16_C(64852)
#define BMA530_STEP_COUNTER_7_STEP_DUR_MEAN_DECAY_COEFF_W   UINT16_C(55706)
#define BMA530_STEP_COUNTER_7_STEP_DUR_MEAN_DECAY_COEFF_H   UINT16_C(58982)

#define BMA530_STEP_COUNTER_8_STEP_BUFFER_SIZE_S            UINT16_C(7)
#define BMA530_STEP_COUNTER_8_STEP_BUFFER_SIZE_W            UINT16_C(4)
#define BMA530_STEP_COUNTER_8_STEP_BUFFER_SIZE_H            UINT16_C(7)

#define BMA530_STEP_COUNTER_8_FILTER_CASCADE_ENABLED_S      UINT16_C(1)
#define BMA530_STEP_COUNTER_8_FILTER_CASCADE_ENABLED_W      UINT16_C(1)
#define BMA530_STEP_COUNTER_8_FILTER_CASCADE_ENABLED_H      UINT16_C(1)

#define BMA530_STEP_COUNTER_8_STEP_COUNTER_INCREMENT_S      UINT16_C(256)
#define BMA530_STEP_COUNTER_8_STEP_COUNTER_INCREMENT_W      UINT16_C(256)
#define BMA530_STEP_COUNTER_8_STEP_COUNTER_INCREMENT_H      UINT16_C(256)

#define BMA530_STEP_COUNTER_8_EN_HALF_STEP_S                UINT16_C(0)
#define BMA530_STEP_COUNTER_8_EN_HALF_STEP_W                UINT16_C(1)
#define BMA530_STEP_COUNTER_8_EN_HALF_STEP_H                UINT16_C(0)

#define BMA530_STEP_COUNTER_9_PEAK_DURATION_MIN_WALKING_S   UINT16_C(12)
#define BMA530_STEP_COUNTER_9_PEAK_DURATION_MIN_WALKING_W   UINT16_C(39)
#define BMA530_STEP_COUNTER_9_PEAK_DURATION_MIN_WALKING_H   UINT16_C(13)

#define BMA530_STEP_COUNTER_9_PEAK_DURATION_MIN_RUNNING_S   UINT16_C(12)
#define BMA530_STEP_COUNTER_9_PEAK_DURATION_MIN_RUNNING_W   UINT16_C(25)
#define BMA530_STEP_COUNTER_9_PEAK_DURATION_MIN_RUNNING_H   UINT16_C(12)

#define BMA530_STEP_COUNTER_10_ACTIVITY_DETECTION_FACTOR_S  UINT16_C(3)
#define BMA530_STEP_COUNTER_10_ACTIVITY_DETECTION_FACTOR_W  UINT16_C(3)
#define BMA530_STEP_COUNTER_10_ACTIVITY_DETECTION_FACTOR_H  UINT16_C(3)

#define BMA530_STEP_COUNTER_10_ACTIVITY_DETECTION_THRES_S   UINT16_C(3900)
#define BMA530_STEP_COUNTER_10_ACTIVITY_DETECTION_THRES_W   UINT16_C(3900)
#define BMA530_STEP_COUNTER_10_ACTIVITY_DETECTION_THRES_H   UINT16_C(3900)

#define BMA530_STEP_COUNTER_11_STEP_DURATION_MAX_S          UINT16_C(74)
#define BMA530_STEP_COUNTER_11_STEP_DURATION_MAX_W          UINT16_C(150)
#define BMA530_STEP_COUNTER_11_STEP_DURATION_MAX_H          UINT16_C(74)

#define BMA530_STEP_COUNTER_11_STEP_DURATION_WINDOW_S       UINT16_C(160)
#define BMA530_STEP_COUNTER_11_STEP_DURATION_WINDOW_W       UINT16_C(160)
#define BMA530_STEP_COUNTER_11_STEP_DURATION_WINDOW_H       UINT16_C(160)

#define BMA530_STEP_COUNTER_12_EN_STEP_DUR_PP_S             UINT16_C(0)
#define BMA530_STEP_COUNTER_12_EN_STEP_DUR_PP_W             UINT16_C(1)
#define BMA530_STEP_COUNTER_12_EN_STEP_DUR_PP_H             UINT16_C(1)

#define BMA530_STEP_COUNTER_12_STEP_DUR_THRES_S             UINT16_C(0)
#define BMA530_STEP_COUNTER_12_STEP_DUR_THRES_W             UINT16_C(3)
#define BMA530_STEP_COUNTER_12_STEP_DUR_THRES_H             UINT16_C(3)

#define BMA530_STEP_COUNTER_12_EN_MCR_PP_S                  UINT16_C(0)
#define BMA530_STEP_COUNTER_12_EN_MCR_PP_W                  UINT16_C(1)
#define BMA530_STEP_COUNTER_12_EN_MCR_PP_H                  UINT16_C(1)

#define BMA530_STEP_COUNTER_12_MCR_THRES_S                  UINT16_C(0)
#define BMA530_STEP_COUNTER_12_MCR_THRES_W                  UINT16_C(14)
#define BMA530_STEP_COUNTER_12_MCR_THRES_H                  UINT16_C(8)

#define BMA530_SIG_MOTION_1_BLOCK_SIZE_S                    UINT16_C(250)
#define BMA530_SIG_MOTION_1_BLOCK_SIZE_W                    UINT16_C(250)
#define BMA530_SIG_MOTION_1_BLOCK_SIZE_H                    UINT16_C(250)

#define BMA530_SIG_MOTION_2_P2P_MIN_S                       UINT16_C(60)
#define BMA530_SIG_MOTION_2_P2P_MIN_W                       UINT16_C(150)
#define BMA530_SIG_MOTION_2_P2P_MIN_H                       UINT16_C(38)

#define BMA530_SIG_MOTION_2_MCR_MIN_S                       UINT16_C(11)
#define BMA530_SIG_MOTION_2_MCR_MIN_W                       UINT16_C(8)
#define BMA530_SIG_MOTION_2_MCR_MIN_H                       UINT16_C(8)

#define BMA530_SIG_MOTION_3_P2P_MAX_S                       UINT16_C(595)
#define BMA530_SIG_MOTION_3_P2P_MAX_W                       UINT16_C(595)
#define BMA530_SIG_MOTION_3_P2P_MAX_H                       UINT16_C(400)

#define BMA530_SIG_MOTION_3_MCR_MAX_S                       UINT16_C(17)
#define BMA530_SIG_MOTION_3_MCR_MAX_W                       UINT16_C(17)
#define BMA530_SIG_MOTION_3_MCR_MAX_H                       UINT16_C(17)

#ifdef __cplusplus
}
#endif /* End of CPP guard */

#endif /* _BMA530_CONTEXT_H */
